# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CFN
brief-intro: "Cybertron fake news. By fans, for fans."
baseurl: "/cybertron-fake-news" # the subpath of your site, e.g. /blog
url: "https://largecats.github.io/" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/
future: true

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
plugins: [jekyll-paginate]
paginate: 5

theme: jekyll-theme-slate